baseURL: https://example.com
languageCode: en
DefaultContentLanguage: en
title: Nemanja Vaci
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
taxonomies:
  category: categories
  series: series
  tag: tags

params:
  title : "Nemanja Vaci"
  author : "Nemanja Vaci"
  description : "Lecturer in Psychology"
